- README.md
> Write the first version's specifications

- .scalafmt.conf
- README.md
* Fix CI: add .scalafmt.conf
* Fix Spec: `output` option is required, so write so.
> Fix CI & Fix README specification

- README.md
I think this plugin is not for EMR.
> EMR -> Athena

- src/main/scala/pro/civitaspo/digdag/plugin/athena/operator/AthenaQueryOperator.scala
* Wrap AmazonS3URI constructor to prevent path from uri-encoding
> Fix: `output` is uri encoded

- CHANGELOG.md
- README.md
- build.gradle
- example/example.dig
* [Fix] `athena.ctas>` Skip removing objects if removable targets do not exist.
> Ship v0.1.1

- README.md
- src/main/scala/pro/civitaspo/digdag/plugin/athena/operator/AthenaCtasOperator.scala
* [Fix] `athena.ctas>` Use normalized table name by default.
> [athena.ctas] Use normalized table name by default

- CHANGELOG.md
- README.md
- build.gradle
- example/example.dig
* [Fix] `athena.ctas>` Use normalized table name by default.
> Ship v0.1.2

- CHANGELOG.md
- README.md
- build.gradle
- example/example.dig
* [New Feature] Add supporting to use Amazon S3 file for query execution
> Ship v0.1.4

- src/main/scala/pro/civitaspo/digdag/plugin/athena/operator/AthenaCtasOperator.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/operator/AthenaQueryOperator.scala
* Show failure message if loading query on s3 is failed
* Show success or ignored failure message as debug message
> Expose more logs when loading queries

- README.md
- src/main/scala/pro/civitaspo/digdag/plugin/athena/operator/AthenaCtasOperator.scala
* Use an unique table name as default in `athena.ctas>`
> [athena.ctas] Use an unique table name as default

- CHANGELOG.md
- README.md
- build.gradle
- example/example.dig
* [Enhancement] Expose more logs when loading queries.
* [Enhancement] * Use an unique table name as default in `athena.ctas>`
> Ship v0.1.5

- .circleci/config.yml
- src/main/scala/pro/civitaspo/digdag/plugin/athena/AbstractAthenaOperator.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/AthenaPlugin.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/aws/AmazonS3UriWrapper.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/aws/Aws.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/aws/AwsConf.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/ctas/AthenaCtasOperator.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/preview/AthenaPreviewOperator.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/query/AthenaQueryOperator.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/wrapper/RetryExecutorWrapper.scala
* Remove spotless from CI
* Reformat by Intellij
> Remove ci spotless

- README.md
- build.gradle
- example/example.dig
- src/main/scala/pro/civitaspo/digdag/plugin/athena/AbstractAthenaOperator.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/AthenaPlugin.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/add_partition/AthenaAddPartitionOperator.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/aws/Aws.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/aws/glue/Glue.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/aws/glue/catalog/DatabaseCatalog.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/aws/glue/catalog/PartitionCatalog.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/aws/glue/catalog/TableCatalog.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/aws/s3/S3.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/ctas/AthenaCtasOperator.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/drop_partition/AthenaDropPartitionOperator.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/drop_table/AthenaDropTableOperator.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/preview/AthenaPreviewOperator.scala
* [Enhancement] Use scala 2.13.0
* [New feature] `athena.add_partition>` operator
* [New feature] `athena.drop_partition>` operator
* [New feature] `athena.drop_table>` operator
* [Enhancement] Suppress aws-java-sdk log
* [Note] Use aws-java-sdk-glue for catalog only operations.
> Add some simple operators

- README.md
- example/example.dig
- src/main/scala/pro/civitaspo/digdag/plugin/athena/AthenaPlugin.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/apas/AthenaApasOperator.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/apas/AthenaDiffSchemaInternalOperator.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/aws/glue/catalog/PartitionCatalog.scala
* Add `athena.apas>` operator.
> Add `athena.apas>` operator

- build.gradle
- src/main/scala/pro/civitaspo/digdag/plugin/athena/AbstractAthenaOperator.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/aws/AwsService.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/aws/athena/Athena.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/aws/athena/AthenaQueryWaiter.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/aws/sts/Sts.scala
* [Enhancement] Introduce scala-logging
* [Enhancement] Use the workgroup default location as athena query output location
> Use wg output

- README.md
- example/example.dig
- src/main/scala/pro/civitaspo/digdag/plugin/athena/ctas/AthenaCtasOperator.scala
* [Change] Introduce `location` option and `output` option become deprecated for `athena.ctas>`
> Introduce location option and output option become deprecated for athena.ctas>

- README.md
- example/example.dig
- src/main/scala/pro/civitaspo/digdag/plugin/athena/AthenaPlugin.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/aws/athena/Athena.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/aws/glue/catalog/TableCatalog.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/drop_table_multi/AthenaDropTableMultiOperator.scala
* [New Feature] Add `athena.drop_table_multi>` operator
* [Enhancement] Expose the real error message and state when the query execution is failed.
> Drop tables

- CHANGELOG.md
- README.md
- build.gradle
- example/example.dig
* [New Feature] Add `athena.drop_table_multi>` operator
* [Enhancement] Expose the real error message and state when the query execution is failed.
> Ship v0.2.3

- CHANGELOG.md
- README.md
- build.gradle
- example/example.dig
* [New Feature] Add `athena.table_exists?>` operator
* [New Feature] Add `athena.partition_exists?>` operator
> Ship v0.2.4

- src/main/scala/pro/civitaspo/digdag/plugin/athena/AthenaPlugin.scala
- [Fix] Catch any initialization exception and re-throw as `ConfigException`
> Catch any initialization exception and re-throw as ConfigException

- CHANGELOG.md
- README.md
- build.gradle
- example/example.dig
* [Fix] Catch any initialization exception and re-throw as `ConfigException`
> Ship v0.2.5

- README.md
- example/example.dig
- src/main/scala/pro/civitaspo/digdag/plugin/athena/AthenaPlugin.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/aws/glue/catalog/DatabaseCatalog.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/aws/glue/catalog/TableCatalog.scala
- src/main/scala/pro/civitaspo/digdag/plugin/athena/each_database/AthenaEachDatabaseOperator.scala
* [Fix] `aws.glue.list` bug: `limit` does not work correctly.
* [New feature] Add `athena.each_database>` operator
> Add `athena.each_database>` operator
